version: "3"
services:
  service.mongodb:
    container_name: mongodb
    image: "mongo:latest"
    networks:
      - all_in_one_network
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./server/db_data:/data/db

  express_server:
    container_name: express
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - all_in_one_network
    depends_on:
      - service.mongodb
    volumes:
      - ./server/logs:/logs

  web_mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - 8090:80
    networks:
      - all_in_one_network
    depends_on:
      - express_server

networks:
  all_in_one_network:
# volumes:
#   all_in_one_data:
